### ISSUE TITLE
Save and load models

### ISSUE THREAD

**Issue by jk556** [KindXiaoming/pykan#353]
I change save_ckpt  to saveckpt and save sth.  But loadckpt doesn't work and it errors that there is no object with this name. What is the procedure of saving models and load them in another machine without starting the training from the first steps!
Tnx

**Comment by KindXiaoming** [comment]
```python
path = './model'
model.saveckpt(path)
model = KAN.loadckpt(path)
```
also in the most recent version, `auto_save=True` is turned on by default, so the models are automatically saved in ckpt_path (by default ckpt_path = './model'). To set it the path, use `model(... ckpt_path=your_path)`

**Comment by jk556** [comment]
Unfortunately it errors again, another question ; how to use it to predict a new input value?
Model([,,,]) or model.predict was not defined.
![Uploading 20240722_124312.jpg…]()

**Comment by jk556** [comment]
![20240722_124312](https://github.com/user-attachments/assets/60733f89-53e1-495e-aaeb-e0f6ffa3ca2e)

**Comment by KindXiaoming** [comment]
(1) the first image seems broken.

(2) could you just try what `KAN.loadckpt` returns? The method is defined here: https://github.com/KindXiaoming/pykan/blob/master/kan/MultKAN.py#L252

**Comment by jk556** [comment]
![172181873228941352226343388165](https://github.com/user-attachments/assets/6fe73cb3-23d4-48d9-8e8b-14c7108f37ff)
Hi, thanks for your responses
In my installation folder, I have a multikan.py which doesn't have loadckpt. Instead of that, I have a ckpt.py which have it. I reinstalled pykan 0.2.1 from pypi again, and it has the same results.
Thanks

**Comment by KindXiaoming** [comment]
thanks for the report! The github code is always up to date, but the pypi may lag behind. Just released 0.2.2, which should solve the problem!

**Comment by jk556** [comment]
I ran it again (0.2.3). It has two error
At last step 50/50; we have:
![20240727_192530](https://github.com/user-attachments/assets/0fffb963-43d9-469b-b38a-6964c7537e5b)

I skipped and saved the model separately. Then try to load it; new error was:
![20240727_192333](https://github.com/user-attachments/assets/74887252-9e75-4162-be3c-4fb77b939839)

It is good to mention that when I tried to load old saved model, this error occurred too.

**Comment by jk556** [comment]
I tried again. The second problem is just for old saved models. But the first error is still persisting. I think another person point to these errors in newer issues.
